#=================================================
# Description: Build Android HAL using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
#=================================================

name: Build Android HAL

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build-hal:
    runs-on: ubuntu-16.04

    env:
      DEVICE: vince
      VENDOR: xiaomi
      ANDROID_ROOT: /home/runner/work/hadk_14.1/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git


    - name: Initialization repo
      run: |
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "BirdZhang"
        git config --global user.email "0312birdzhang@gmail.com"

    - name: Downloading source code
      run: |
        source hadk.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u git://github.com/mer-hybris/android.git -b hybris-14.1 --depth=1
        repo sync -j8 -c --no-clone-bundle --no-tags
        repo sync
    
    - name: Clone device spec source
      run: |
        source hadk.env
        git clone https://github.com/Sailfish-On-Vince/device_xiaomi_vince.git $ANDROID_ROOT/device/xiaomi/vince --depth=1
        git clone https://github.com/Sailfish-On-Vince/vendor_xiaomi_vince.git $ANDROID_ROOT/vendor/xiaomi/vince --depth=1
        git clone https://github.com/Sailfish-On-Vince/Xiaomi_Kernel_OpenSource.git $ANDROID_ROOT/kernel/xiaomi/msm8953 --depth=1
        rm -rf $ANDROID_ROOT/hybris/hybris-boot
        git clone https://github.com/Sailfish-On-Vince/hybris-boot.git $ANDROID_ROOT/hybris/hybris-boot
        git clone https://github.com/Sailfish-On-Vince/droid-hal-vince.git $ANDROID_ROOT/rpm


    # - name: SSH connection to Actions
    #   uses: P3TERX/debugger-action@master

    - name: Build HAL
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: hybris-boot.img
        path: /home/runner/work/hadk_14.1/out/target/product/vince/hybris-boot.img

  build-mer:
    needs: build-hal
    runs-on: ubuntu-16.04
    container:
      image: docker://coderus/sailfishos-platform-sdk-base:3.1.0.12
    env:
      DEVICE: vince
      VENDOR: xiaomi
      ANDROID_ROOT: /home/runner/work/hadk_14.1/

    steps:
    - name: Checkout
#       uses: actions/checkout@master
      run: |
        git clone https://github.com/Sailfish-On-Vince/ci
        cp ci/build-rpm.sh $ANDROID_ROOT
        cp ci/hadk.env $ANDROID_ROOT

    - name: Build dhd in container
      run: |
        cd $ANDROID_ROOT
        chmod +x build-rpm.sh
        bash -x build-rpm.sh
      shell: bash
    
    - name : Upload mer packages
      uses: actions/upload-artifact@master
      with:
        name: Mer packages
        path: /home/runner/work/hadk_14.1/droid-local-repo.zip
